### ISSUE TITLE
Could not find GoogleNews-vectors-negative300.bin.gz

### ISSUE THREAD

**Issue by jonico** [toludwig/golden-lemurs#1]
@toludwig @MSchuwalow @fabrichter: While trying to create the docker image, your script complains that GoogleNews-vectors-negative300.bin.gz cannot be unzipped, can you add it to this repo or should I exclude it from the Dockerfile?

**Comment by MSchuwalow** [comment]
Thanks for the quick feedback. The file is required for our classifier to work, so please don't exclude it from the Dockerfile. Instead please download the file from https://drive.google.com/file/d/0ByJXV7reBQxTa3Zzbk4tVUE0UVE and place it into the data directory of our repository (don't extract it yourself).
